### ISSUE TITLE
How to edit blobs?

### ISSUE THREAD

**Issue by shijianjian** [dave-epstein/blobgan#4]
Hi,

Thanks for the repo. It is pretty interesting to play around.

I am wondering how do I edit the blobs to make things vanish? Presumably, I will be editing the outputs from the inversion models, right? So, how should I do that?

Best,
Jian

**Comment by dave-epstein** [comment]
Hi,

I'm not sure I understand the connection to the inversion model (which would only be used if you wanted to remove things from a real image vs. a generated one). For a code example of resizing/removing a blob, you can do this:

```python
layout = model.generate_layout(z, truncate=truncate, **model.render_kwargs)
layout['sizes'][batch_idx, [i + 1 for i in blob_idxs]] -= delta
new_layout, img = model.gen(layout=layout, **model.render_kwargs)

# Visualize in notebook
from torchvision.utils import make_grid
import torchvision.transforms.functional as F
F.to_pil_image(make_grid(out, normalize=True))
```

For more examples of how to change layout to modify the rendered image, you can see [here](https://github.com/dave-epstein/blobgan/blob/fe5dde66891c8feebfa460a3f244fa7c2ba557f3/src/utils/colab.py#L320).

Hope this helps!

**Comment by tejank10** [comment]
Hi @dave-epstein , great work and thanks for making the code public!

Can you also show us how to get the results in Fig. 6 of the paper, where the styles are swapped? I tried by simply swapping the style vectors (spatial style) of the blob corresponding to the bed, splatting the features, and regenerating the image, but could observe hardly any changes in the image?

Below is the result that I get. Can you please point out what's the correct way to obtain these results? Thank you.
<img width="517" alt="image" src="https://user-images.githubusercontent.com/19868340/176272860-f98b92b0-9334-4a5c-bc0e-f21392cbe940.png">
