### ISSUE TITLE
Regarding the running time

### ISSUE THREAD

**Issue by 1Konny** [dave-epstein/blobgan#6]
Hi. 

While reading the paper, I'm a little bit confused of the training time for the BlobGAN.

Specifically, in the Appendix E.1 in the paper, it is written as "We train all models for 1.5 million gradient steps with batch size 24 per-GPU across 8 NVIDIA A100 GPUs. This takes around 4 weeks." 

Now I'm wondering if it takes 4 weeks with 8 NVIDIA A100 GPUs for training **a single model** or for **all models**. 

Could you please clarify this more?

Thanks!

**Comment by dave-epstein** [comment]
That's how long it takes for each model :)

**Comment by 1Konny** [comment]
Thanks a lot for your quick response!
