### ISSUE TITLE
Inversion

### ISSUE THREAD

**Issue by zmehdiz97** [dave-epstein/blobgan#7]
Hi,

I have a question regarding image inversion. To train the encoder, did you use the jittering of the spatial parameters? In the 'invertblobgan.py' code no_jitter is not used and the invertblobgan.yaml doesn't set the jittering parameters to 0. Is this intended?

**Comment by dave-epstein** [comment]
We do not train with jittering for inversion. [The default jitter values are 0](https://github.com/dave-epstein/blobgan/blob/main/src/models/blobgan.py#L92) so there's no need to explicitly specify jitter 0. Only the weights are loaded from the generator, the config used is the one supplied on the command line.
