### ISSUE TITLE
Cannot reproduce a layout

### ISSUE THREAD

**Issue by shijianjian** [dave-epstein/blobgan#8]
Hi,

I cannot reproduce with the same layout
```python
layout, img = model.gen(z, ret_layout=True)
layout, img = model.gen(layout=layout, ret_layout=True)
```

https://github.com/dave-epstein/blobgan/blob/c527f1c27447dffe3cf4cf3901571a83ce59f1fe/src/models/blobgan.py#L303

https://github.com/dave-epstein/blobgan/blob/c527f1c27447dffe3cf4cf3901571a83ce59f1fe/src/models/blobgan.py#L323

I am wondering the basis computation is wrong here, which you will get a tensor with shape `BxCx2x0`:
https://github.com/dave-epstein/blobgan/blob/c527f1c27447dffe3cf4cf3901571a83ce59f1fe/src/models/blobgan.py#L327

**Comment by dave-epstein** [comment]
Yes, the shape of `covs` is actually not N x M x 2 x 2 unless `covs_raw` is False, sorry about that. If you run the code you'll see it's an N x M x 4 packed tensor of all the blob parameters which is then processed into the final covariance matrix. Apologies for the misleading code segment!

**Comment by shijianjian** [comment]
Hi @dave-epstein,

Thanks for the explanation. I run the following code:

```python
layout, img = model.gen(layout=layout, ret_layout=True)
```

It turns out that  the bug appeared (that NM22 is outputted) when the `layout` is provided. As a result, a simple reshape from `NM22` to `NM4` would work, right?

**Comment by dave-epstein** [comment]
That should not be necessary. I've run that code snippet that you sent without any problem. See this line which takes care of the correct parameter settings automatically: https://github.com/dave-epstein/blobgan/blob/main/src/models/blobgan.py#L183

Do you have an old version of the code or something like that?

**Comment by shijianjian** [comment]
It worked after updating the code to the latest version. Thanks.
